HW04 completed
VladislavTyurin/OTUS-Golang pull request #4
Opened 2023-03-05 10:13 UTC by VladislavTyurin

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-03-07 20:34 UTC, vladislavmass requested changes
Работа хорошая. Радует правильное имя модуля. Есть ряд замечаний к реализации листа. Пока работу принять не могу.

2023-03-07 20:34 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +			if i == l.first {
Не обработана ситуация когда удаляется первый или последний элемент в списке из более чем 1 элемента.

2023-03-07 20:34 UTC, hungry-honeybadger commented on hw04_lru_cache/list.go
> +	if i != l.first && i != nil {
Не обработана ситуация переноса из конца в начало.

2023-03-08 07:44 UTC, VladislavTyurin commented on hw04_lru_cache/list.go
> +	if i != l.first && i != nil {
@vladislavmass поправил

2023-03-08 07:44 UTC, VladislavTyurin commented on hw04_lru_cache/list.go
> +			if i == l.first {
@vladislavmass поправил

2023-03-09 06:49 UTC, vladislavmass approved these changes
Работа принята. 10/10.

2023-03-09 08:08 UTC, merged